### ISSUE TITLE
Need Time due to arcs and tasks

### ISSUE THREAD

**Issue by KevinKelly25** [smacademic/project-cgkm#121]
Currently there is no way for users to see what time a task or arc is due by, they can only see the date. In order to add time we can do two things:

1) Make the `dueDate` in arc and task also contain the time
2) Add another time attribute to both arc and task

I believe it is best to go with option 2 as many of our date related functions compare date strings and adding time to the end of the strings may make functions more complicated then needed.

**Comment by MatthewChastain** [comment]
I would also opt for option 2 as not all tasks will want a time associated with them and option 2 allows for this.

**Comment by jrm86** [comment]
I agree with @MatthewChastain. An additional, optional attribute in the DB would work.

**Comment by jgrabowski121** [comment]
I also agree with the previous reply that option 2 would be preferable
