### ISSUE TITLE
Need Insert, Update, Delete operations

### ISSUE THREAD

**Issue by jrm86** [smacademic/project-cgkm#18]
PR #17 completes the DB framework, but did not address Insert, Update, or Delete operations. While addressed as part of issue #10, some parts of the implementation would have crossed paths with portions of the app which are still being designed at the time this message is being written.  

Possible workarounds are:
- Prioritize design and implementation of applicable classes
- Build "skeleton" classes with only the DB portions needed for Insert, Update, and Delete ops

**Comment by jgrabowski121** [comment]
This issue was closed by PR #35
