### ISSUE TITLE
Schema documentation is out of date

### ISSUE THREAD

**Issue by jrm86** [smacademic/project-cgkm#19]
During the review of PR #11, we identified an error in our documentation. Composite keys were used where they were not needed.

Logical, Normalized, and Optimized schemas, in addition to the table summaries need to be updated in the [wiki](https://github.com/smacademic/project-cgkm/wiki).

**Comment by jrm86** [comment]
I think a good way to go about the change would be to make all needed changes to the wiki repo, then copy/pasting all files into this repo's docs folder. I believe this is what @KevinKelly25 was talking about in earlier conversations (please correct me if I'm wrong).

**Comment by KevinKelly25** [comment]
You are right. Thank you for making this issue @jrm86. I am working on this now with the fix mentioned in PR #11
