### ISSUE TITLE
Need classes for ArcUser, Arc, and Task

### ISSUE THREAD

**Issue by jrm86** [smacademic/project-cgkm#22]
The app does not have classes to represent the entities in the DB. These classes will be needed for the app to interact with the database. 

My recommendation is to begin implementing the classes in the [model](https://github.com/smacademic/project-cgkm/tree/dev/client/src/arcplanner/lib/model) folder.

Related to issue #18.

**Comment by jrm86** [comment]
This and issue #18 is being addressed in the [create-classes](https://github.com/smacademic/project-cgkm/tree/create-classes) branch.

**Comment by jrm86** [comment]
As of [this commit](https://github.com/smacademic/project-cgkm/commit/e7dd02b26cb4d3cbcc9b66ae8c18c80f7fcf31f8), a basic insert operation has been implemented. That being said, SQLite does not have support for UUIDs. It can store them perfectly fine, but cannot generate them. Probably worth a discussion at some point.

**Comment by jrm86** [comment]
[This flutter package](https://pub.dartlang.org/packages/uuid) might be a good solution.

**Comment by KevinKelly25** [comment]
The above mentioned package looks good for generating IDs. I believe the best function to meet our needs is the `uuid.v4` function of the UUID package. From what I have seen in your commits it is coming along well.
