### ISSUE TITLE
Need Standardized File Headers

### ISSUE THREAD

**Issue by MatthewChastain** [smacademic/project-cgkm#58]
Currently, there are a number of different file headers being used in the project. We need to implement a standard format for file headers throughout ArcPlanner's files. This includes all created files, regardless of language used. At this time, I believe the header should include the names of the people who worked on the file, the course number and name, semester it was developed in, Use at own risk statement, and a brief summary of the file's contents.

**Comment by KevinKelly25** [comment]
In order to avoid many merge conflicts, which is a high possibility with this type of issue. I believe this issue should be resolved at the very end of the milestone right before release when all other PRs are closed. This can and possibly should be done with issue #60 

I am unsure of the best format for comment but I do think it would be a good idea to have filename at the top and then at some point a list of names of people who worked on the file. The idea being that if you name is on the file you have familiarity with it and should be able to answer questions about it if needed.

**Comment by jrm86** [comment]
I've created a [Wiki page](https://github.com/smacademic/project-cgkm/wiki/Standardized-file-header-and-function-comments) so that we can view, edit, and comment upon file header format without risking merge conflicts.

**Comment by MatthewChastain** [comment]
For the file headers, I personally think it would be better to have "Team CGKM" on its own separate line like such: 
```
/** 
 *  filename.dart
 *  Matthew Chastain, Justin Grabowski, Kevin Kelly, Jonathan Middleton
 *  CS298 Spring 2019 
 *  Team CGKM 
 * 
 *  Provided as is. No warranties expressed or implied. Use at your own risk.
 *
 *  This file contains...
 */
```
Other thoughts on this?

Also do we want the file name in the header? I remember us talking about that being not great when it comes to version control systems and it seems redundant.

**Comment by KevinKelly25** [comment]
I like this format @MatthewChastain. I am more in favor of not including the filename as I can't think of a good reason to keep them. For the names would they be everyone or just the people who worked on the file?

**Comment by MatthewChastain** [comment]
I think we should include primary authors of each file in the header as their own section. Perhaps something like: 
```
/** 
 *  Authors: 
 *    Primary: Justin Grabowski, Kevin Kelly, Jonathan Middleton
 *    Other: Matthew Chastain
 *  CS298 Spring 2019 
 *  Team CGKM 
 * 
 *  Provided as is. No warranties expressed or implied. Use at your own risk.
 *
 *  This file contains...
 */
```

If someone hasn't worked on the file at all then I wouldn't necessarily say they should be included in the header. Personally I wouldn't want to be included in the header of a file I hadn't worked on.

**Comment by KevinKelly25** [comment]
I would be okay with that approach or not mentioning authors who didn't contribute. I think we should wait to see which approach @jgrabowski121 and @jrm86 thinks is better?

**Comment by MatthewChastain** [comment]
So my suggestion is have the main authors listed as `Primary` and then anyone else who works on the file listed as `Other`. If someone doesn't contribute to a file then they aren't listed in either category.

**Comment by jgrabowski121** [comment]
@MatthewChastain , I believe that this approach works with minor adjustments. I believe "other" should be "contributors" or possibly something that sounds more succinct. I also would like the Team CGKM line to have all team members listed. It is tough to define an "other" author or "contributor" when all team members are expected to review all files and the definition of author can be subjective. Therefore, if the line that says "Team CGKM" has all team members listed, then only those who actually write to the file should be an author.

I think this approach would allow us to have a clear set of rules for who is considered an author because although I agree that I do not need credit for a file I did not work on I acknowledge that everyone is expected to review and reviewing is work and contribution. Additionally, if I mainly write a file I still consider the reviewing a substantial contribution but please respond with your thoughts I am still open to a difference of opinion.

Edit: Reworded for clarity

**Comment by jgrabowski121** [comment]
Additionally, I believe that if a mistake is made within a file that is merged, the blame belongs to all members of the Team because our project requires all members to review. I think this is best reflected by having all Team members names at least being on every file but not as authors.

**Comment by MatthewChastain** [comment]
I agree that if we merge a mistake all members are responsible for it, however I believe this is taken care of just by having `Team CGKM` in the header. I don't believe there is a reason to list the members as that information is readily available in the project repo itself. While I do agree that review is a large contribution, it doesn't make someone an author in my mind unless they make corrections to the file. Thoughts on this?

I am fine with changing `Other` to something like `Secondary` or `Contributors` depending on the rest of the team's thoughts.

**Comment by jgrabowski121** [comment]
@MatthewChastain, I agree that it does not make someone and author when they review but my point was not to have them listed as authors but rather to have the team members who were active at the time be acknowledged and I apologize If that was not clear. I do however agree that the team members are available within the project repo and this can be sufficient. The only reason I see for naming the members explicitly is that the Team may expand (or shrink) in the future, and the Team members who were active when a file was created/ edited may change. However, I am okay with the understanding that the Team members are accessed in the repo itself we can omit the names, but I thought it was worth discussing.

**Comment by KevinKelly25** [comment]
I agree with @jgrabowski121 to have authors be the people who worked on the file and then the lines that says team CGKM can be `Team CGKM - Matthew Chastain, Justin Grabowski, Kevin Kelly, Jonathan Middleton`

It isn't a super scalable solution but it probably will work. At the very least it will work until we grow out of Team CGKM.

Edit: misread previous comments and had to reword

**Comment by MatthewChastain** [comment]
I hadn't really considered team members changing but I suppose it could happen at some point down the road. How does this look for a standard format then?
```
/** 
 *  Team CGKM - Matthew Chastain, Justin Grabowski, Kevin Kelly, Jonathan Middleton
 *  CS298 Spring 2019 
 *
 *  Authors: 
 *    Primary: Justin Grabowski
 *    Contributors: Kevin Kelly, Jonathan Middleton
 * 
 *  Provided as is. No warranties expressed or implied. Use at your own risk.
 *
 *  This file contains...
 */
```
Any changes that need to be made?

**Comment by KevinKelly25** [comment]
@MatthewChastain  What would be the difference between Primary and Contributors in this format?

**Comment by MatthewChastain** [comment]
@KevinKelly25 Primary author would be the creator(s) of the file or large contributors. Contributors, Other, or Secondary (depending on which we decide is best) would be members of the team that corrected small errors or made minor changes to the file during the development/maintenance process.

**Comment by KevinKelly25** [comment]
I like that idea. I think your format is the best way to go unless someone else has a suggestion

**Comment by jrm86** [comment]
Sorry, late to the party. I think it might be borderline redundant to list names after `Team CGKM`. Given the workflow we're using, it's likely that most or all of us would be either an author or contributor. I don't want to be a show-stopper, though, if everyone else would prefer that it stays.

**Comment by KevinKelly25** [comment]
You may be right @jrm86. Maybe we should try out the method by @MatthewChastain for a couple or few milestones and then if we see a lot of redundancy as mentioned then we can reopen this discussion?

**Comment by jgrabowski121** [comment]
> I hadn't really considered team members changing but I suppose it could happen at some point down the road. How does this look for a standard format then?
> 
> ```
> /** 
>  *  Team CGKM - Matthew Chastain, Justin Grabowski, Kevin Kelly, Jonathan Middleton
>  *  CS298 Spring 2019 
>  *
>  *  Authors: 
>  *    Primary: Justin Grabowski
>  *    Contributors: Kevin Kelly, Jonathan Middleton
>  * 
>  *  Provided as is. No warranties expressed or implied. Use at your own risk.
>  *
>  *  This file contains...
>  */
> ```
> Any changes that need to be made?

I agree with @KevinKelly25  that for now we should implement this approach as suggested by @MatthewChastain

**Comment by MatthewChastain** [comment]
Closing this issue.
